language: node_js
node_js:
- 0.12.7
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_1ee748c23a20_key -iv $encrypted_1ee748c23a20_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "zoorz"
- git config --global user.email zoechow8@gmail.com
install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
